### ISSUE TITLE
Environment failure due to incompatible of v3.0.0 with ipython

### ISSUE THREAD

**Issue by fcollonval** [AnacondaRecipes/prompt_toolkit-feedstock#1]
prompt_tookit v3 package has been release on the defaults channel:

```
prompt_toolkit 3.0.0 py_0
-------------------------
file name   : prompt_toolkit-3.0.0-py_0.tar.bz2
name        : prompt_toolkit
version     : 3.0.0
build       : py_0
build number: 0
size        : 232 KB
license     : BSD-3-Clause
subdir      : noarch
url         : https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.0-py_0.tar.bz2
md5         : 65a66495154c9675a024cc3401de8c3e
timestamp   : 2019-11-27 13:03:09 UTC
dependencies:
  - pygments
  - python >=3.6
  - six >=1.9.0
  - wcwidth
```
But it is not compatible with ipython>=7.9. 

I can update the recipe of ipython to avoid that clash as it was done in conda-forge. But I don't know what is your process for that?

**Comment by jjhelmus** [comment]
IPython 7.10.1 packages are now available which are compatible with prompt_toolkit 3.0.2 which is also available.  

I'm looking into hotfixing the older ipython repodata to add an upper bound on prompt_toolkit.

**Comment by fcollonval** [comment]
Thanks @jjhelmus

**Comment by jjhelmus** [comment]
Hotfix has been applied to the packages in `defaults`.  New environment containing ipython>7.0,<7.10 will be restricted to prompt_toolkit>=2.0,<3.
